### ISSUE TITLE
Missing from shinydex

### ISSUE THREAD

**Issue by M-83** [tjvantoll/GOChecklists#11]
First off, I love your checklist!  It's one of the only ones that doesn't have 700 costumed pokemon clogging the screen.

I did notice that the porygon/porygon 2/porygon z and slakoth/vigoroth/slaking lines were missing from the shinydex

**Comment by aeacusetero** [comment]
I saw Porygon family is in there but still no Slakoth line!

**Comment by aeacusetero** [comment]
Also Nosepass/Probopass and Obstagoon

**Comment by tjvantoll** [comment]
Hey all,

Thanks for the compliments and sorry it took forever for me to get back to updating this.

The list should now be totally up to date if you’re still around and interested https://gochecklists.app.
